name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Android App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install Android Workload
        run: dotnet workload install android

      - name: Build APK
        run: dotnet publish GalaxyBudsClient.Android/GalaxyBudsClient.Android.csproj -c Release -p:AndroidPackageFormat=apk -p:AndroidKeyStore=false -p:TreatWarningsAsErrors=false

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: GalaxyBudsClient-APK
          path: '**/*.apk'
          
