name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install Android Workload
        run: dotnet workload install android

      - name: Restore Dependencies
        run: dotnet restore GalaxyBudsClient.Android/GalaxyBudsClient.Android.csproj

      - name: Build APK
        run: dotnet build GalaxyBudsClient.Android/GalaxyBudsClient.Android.csproj -c Debug -f net8.0-android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: GalaxyBudsClient-APK
          path: '**/*.apk'
          path: GalaxyBudsClient.Android/bin/Debug/*/*-Signed.apk
          
